import {
  Post1,
  Post2,
  Post3,
  Post4,
  Post5,
  Post6,
  Post7,
  Post8,
  Post9,
  Post10,
  Post11,
  Post12,
  Post13,
  Post14,
} from "./posts/index";
import { PostType } from "./types";

export const postsData: PostType[] = [
  {
    id: "to-nie-tinder-ale-poznajmy-sie-blizej",
    title: "To nie Tinder, ale poznajmy się bliżej",
    post: <Post1 />,
    imageSmall: "/post-assets/post-1-small.jpg",
    imageBig: "/post-assets/post-1-big.jpeg",
    text: "Jest to pierwszy post prezentujący moją osobę. Kim jestem, dokąd zmierzam i dlaczego rozpocząłem prowadzenie bloga? Zapraszam.",
    date: "13.01.25",
    category: "rozkminy",
  },
  {
    id: "typy-prymitywne-i-te-eleganckie-oraz-ich-referencje",
    title: "Typy prymitywne i te eleganckie oraz ich referencje",
    post: <Post2 />,
    imageSmall: "/post-assets/post-2-small.jpg",
    imageBig: "/post-assets/post-2-big.jpg",
    text: "Omawiam typy proste i te złożone, w prosty a nie złożony sposób oraz tłumaczę co to jest referencja.",
    date: "16.01.25",
    category: "javascript",
  },
  {
    id: "js-owy-zycia-krag",
    title: "Frontendowy życia krąg",
    post: <Post3 />,
    imageSmall: "/post-assets/post-3-small.jpeg",
    imageBig: "/post-assets/post-3-big.jpeg",
    text: "Przyglądam się bliżej mechanizmowi Event Loop w JavaScript.",
    date: "20.01.25",
    category: "javascript",
  },
  {
    id: "czy-studia-z-informatyki-daja-plus-10-do-wisdom-na-start-oraz-dostepne-sciezki-nauki",
    title:
      "Czy studia z informatyki dają +10 do wisdom na start oraz dostępne ścieżki nauki",
    post: <Post4 />,
    imageSmall: "/post-assets/post-4-small.jpeg",
    imageBig: "/post-assets/post-4-big.jpeg",
    text: "Moja analiza dostępnych ścieżek do zdobycia pracy jako programista i przemyślenia o studiach.",
    date: "23.01.25",
    category: "nauka",
  },
  {
    id: "dlaczego-programowanie-zniszczylo-moj-zwiazek",
    title: "Dlaczego programowanie zniszczyło mój związek",
    post: <Post5 />,
    imageSmall: "/post-assets/post-5-small.jpeg",
    imageBig: "/post-assets/post-5-big.jpeg",
    text: "Będzie to smutna historia o pięknej miłości zniszczonej przez kod i o mutacjach tablic w JavaScript, ale to tak przy okazji.",
    date: "27.01.25",
    category: "javascript",
  },
  {
    id: "funkcje-i-ich-funkcje-oraz-parametry-i-argumenty",
    title: "Funkcje i ich funkcje oraz parametry i argumenty",
    post: <Post6 />,
    imageSmall: "/post-assets/post-6-small.jpg",
    imageBig: "/post-assets/post-6-big.jpg",
    text: "Tycie kompendium o funkcjach, argumentach i parametrach na przykładach z życia wziętych.",
    date: "03.02.25",
    category: "javascript",
  },
  {
    id: "rest-in-peace-oraz-operator-rozpierniczenia",
    title: "Rest in peace oraz operator rozpierniczenia",
    post: <Post7 />,
    imageSmall: "/post-assets/post-7-small.jpeg",
    imageBig: "/post-assets/post-7-big.jpeg",
    text: "Cóż to ten operator rest i spread. Gdzie tego można użyć? Zobaczmy!",
    date: "10.02.25",
    category: "javascript",
  },
  {
    id: "rezencja-ksiazki-kariera-programisty",
    title: "Recenzja książki Kariera Programisty",
    post: <Post8 />,
    imageSmall: "/post-assets/post-8-small.jpeg",
    imageBig: "/post-assets/post-8-big.jpeg",
    text: "Co wyniosłem z książki Johna Sonmeza o tytule Kariera Programisty. Szczera recenzja.",
    date: "17.02.25",
    category: "książka",
  },
  {
    id: "sila-masa-pie-cie-nie-redukcja",
    title: "Siła, masa, pie...cie? Nie! Redukcja !!!",
    post: <Post9 />,
    imageSmall: "/post-assets/post-9-small.jpg",
    imageBig: "/post-assets/post-9-big.jpg",
    text: "Zrzućmy razem zbędne kilogramy używając metody reduce(). Robimy formę na lato i na lata.",
    date: "24.02.25",
    category: "javascript",
  },
  {
    id: "czy-meta-jest-daleko-i-co-u-mnie",
    title:
      "To już 10 post! Co się wydarzyło od kiedy zacząłem blogować i czy meta jest daleko?",
    post: <Post10 />,
    imageSmall: "/post-assets/post-10-small.jpg",
    imageBig: "/post-assets/post-10-big.jpg",
    text: "Trochę moich przemyśleń o tym co się wydarzyło od czasu pierwszego posta i pytania o przyszłość.",
    date: "03.03.25",
    category: "rozkminy",
  },
  {
    id: "rozrusznik-nie-wytrzymuje-zwalniam-tempo-niestety",
    title: "Rozrusznik nie wytrzymuje. Zwalniam tempo, niestety.",
    post: <Post11 />,
    imageSmall: "/post-assets/post-11-small.jpg",
    imageBig: "/post-assets/post-11-big.jpg",
    text: "Tak, ten smutny kot idealnie przedstawia moją zszarganą duszę. Od teraz posty będą pojawiać się w dwa razy w miesiącu...",
    date: "03.03.25",
    category: "rozkminy",
  },
  {
    id: "kiedy-plaskie-jest-lepsze-od-nieplaskiego",
    title: "Kiedy płaskie jest lepsze od niepłaskiego?",
    post: <Post12 />,
    imageSmall: "/post-assets/post-12-small.jpg",
    imageBig: "/post-assets/post-12-big.jpg",
    text: "Odpowiadam na przewrotne pytanie kiedy płaskie jest lepsze od niepłaskiego (a na programistyczne jak działa metoda flat).",
    date: "31.03.25",
    category: "javascript",
  },
  {
    id: "interface-vs-type-alias-w-typescript",
    title: "Interface vs Type Alias. Kto wygra ten pojedynek?",
    post: <Post13 />,
    imageSmall: "/post-assets/post-13-small.jpg",
    imageBig: "/post-assets/post-13-big.jpg",
    text: "Odwieczna walka co użyć w projekcie, co będzie lepsze, jakie są różnice między tymi zawodnikami? Sprawdźmy!",
    date: "07.04.25",
    category: "typescript",
  },
  {
    id: "w-koncu-code-review-mama-bedzie-dumna",
    title: "W końcu code review. Mama będzie dumna.",
    post: <Post14 />,
    imageSmall: "/post-assets/post-14-small.jpg",
    imageBig: "/post-assets/post-14-big.jpg",
    text: "Opowiadam o swoim pierwszym code review, które miało miejsce jakiś czas temu. Co z tego wyniosłem? I ile wziął psychoterapeuta? Dodatkowo, co tam u mnie.",
    date: "30.04.25",
    category: "rozkminy",
  },
].reverse() as PostType[];
